services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'

#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.17.10
#    ports:
#      - '5601:5601'
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch

#  kafbat-ui:
#    image: kafbat/kafka-ui:e21f6fb
#    ports:
#      - '8082:8080'
#    environment:
#      DYNAMIC_CONFIG_ENABLED: 'true'
#  #      volumes:
#  #        - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  cockroachdb:
    image: cockroachdb/cockroach:v25.3.2
    command: start-single-node --insecure
    ports:
      - "26257:26257"  # SQL client
      - "8081:8080"    # Admin UI
#    volumes:
#      - cockroach-data:/cockroach/cockroach-data
    environment:
      - COCKROACH_DATABASE=bookstore

  kafka:
    image: apache/kafka:4.1.0
    ports:
      - "9092:9092"
    environment:
      # Listeners
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:29093,INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT # Edit for production
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Kraft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      # Cluster and performance
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Required for single cluster
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # Persistence
      KAFKA_LOG_DIRS: /var/lib/kafka/data
#    volumes:
#      - kafka-data:/var/lib/kafka/data

  kafka-connect:
    build:
      context: .
      dockerfile: connectors/connect.Dockerfile
    depends_on:
      - kafka
      - cockroachdb
      - elasticsearch
    ports:
      - "8083:8083"  # Connect REST API
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"

      CONNECT_CONFIG_STORAGE_TOPIC: my_connect_configs
      CONNECT_OFFSET_STORAGE_TOPIC: my_connect_offsets
      CONNECT_STATUS_STORAGE_TOPIC: my_connect_statuses
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    volumes:
      - ./connectors/plugins:/kafka/connect

#volumes:
#  cockroach-data:
#  kafka-data:
#  es-data: