server:
  port:
    8080

spring:
  application:
    name:elastic_search_test

  # elastic
  elasticsearch:
    uris: http://localhost:9200
    username: elastic  # If security enabled
    password: secret  # If security enabled

  # jdbc
  datasource:
    url: jdbc:postgresql://localhost:26257/bookstore?sslmode=disable
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 30000      # 30s
      connection-timeout: 20000 # 20s
      max-lifetime: 1800000     # 30m

  # jpa
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 128
          fetch_size: 128
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
  
  # liquibase
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
  
